Repository prgrms-be-devcourse/NBB1_2_3_Team09, pull requests merged in 2024-11, with the labels that each got.

#26 25: [REFACTOR] 코드 일부 수정
  src/main/kotlin/medinine/pill_buddy/domain/userMedication/service/UserMedicationServiceImpl.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/service/CaretakerServiceImplTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/userMedication/service/UserMedicationServiceImplTest.kt
Labels: 🔨 Refactor

#28 24: [FEAT] 회원 프로필 업로드
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/controller/ProfileController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/dto/ProfileUploadDto.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/entity/Image.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/repository/ImageRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/service/ProfileService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/service/uploader/CaregiverProfileUploader.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/service/uploader/CaretakerProfileUploader.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/service/uploader/ProfileUploader.kt
  src/main/kotlin/medinine/pill_buddy/global/exception/ErrorCode.kt
  src/main/kotlin/medinine/pill_buddy/global/util/UploadUtils.kt
  src/main/resources/application.yml
  src/test/kotlin/medinine/pill_buddy/domain/user/profile/service/ProfileServiceTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/profile/service/uploader/CaregiverProfileUploaderTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/profile/service/uploader/CaretakerProfileUploaderTest.kt
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#29 27: [FEAT] 보호자 삭제
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/service/CaretakerService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/service/CaretakerServiceImpl.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/service/CaretakerServiceImplTest.kt
Labels: ✨ Feature, ✅ Test

#33 4: [FEAT] 알림 등록&전송 기능
  src/main/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationController.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/dto/NotificationDTO.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/provider/SmsProvider.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/service/NotificationService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/repository/CaretakerCaregiverRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/userMedication/repository/UserMedicationRepository.kt
  src/main/kotlin/medinine/pill_buddy/global/exception/ErrorCode.kt
  src/main/resources/application.yml
  src/test/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/repository/NotificationRepositoryTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/service/NotificationServiceTest.kt
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#36 30: [FEAT] 사용자 약 복용 여부 확인
  src/main/kotlin/medinine/pill_buddy/domain/record/dto/RecordDTO.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerController.kt
  src/main/kotlin/medinine/pill_buddy/domain/userMedication/service/UserMedicationService.kt
  src/main/kotlin/medinine/pill_buddy/domain/userMedication/service/UserMedicationServiceImpl.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerControllerTest.kt
Labels: ✨ Feature, ⚙ Setting

#38 5: [FEAT] 보호자 기능
  gradlew.bat
  src/main/kotlin/medinine/pill_buddy/domain/user/caregiver/controller/CaregiverController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caregiver/service/CaregiverService.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caregiver/controller/CaregiverControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caregiver/repository/CaregiverRepositoryTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caregiver/service/CaregiverServiceTest.kt
Labels: 🔨 Refactor

#42 31: [FEAT] 사용자 약 정보 기록 생성 및 수정
  src/main/kotlin/medinine/pill_buddy/domain/record/repository/RecordRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/record/service/RecordService.kt
  src/main/kotlin/medinine/pill_buddy/domain/record/service/RecordServiceImpl.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerController.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/caretaker/service/CaretakerServiceImplTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/userMedication/service/UserMedicationServiceImplTest.kt
Labels: ✨ Feature, ✅ Test

#43 41: [FEAT] 알림 정보 조회
  src/main/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationController.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/dto/UserNotificationDTO.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/service/NotificationService.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/repository/NotificationRepositoryTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/service/NotificationServiceTest.kt
Labels: ✨ Feature, ✅ Test

#45 39: [FEAT] 카카오 소셜 로그인 기능
  build.gradle.kts
  src/main/kotlin/medinine/pill_buddy/domain/user/caregiver/entity/Caregiver.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caregiver/repository/CaregiverRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/entity/Caretaker.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/repository/CaretakerRepository.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/dto/UserDto.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/dto/UserType.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/entity/User.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/controller/OAuthController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/KakaoProfile.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/KakaoTokenResponse.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoOAuthService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/OAuthService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/service/UserService.kt
  src/main/kotlin/medinine/pill_buddy/global/exception/ErrorCode.kt
  src/main/kotlin/medinine/pill_buddy/global/oauth/KakaoProperty.kt
  src/main/resources/application.yml
  src/test/kotlin/medinine/pill_buddy/domain/notification/service/NotificationServiceTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoOAuthServiceTest.kt
  src/test/resources/application.yml
Labels: ✨ Feature

#48 47: [FEAT] 알림 삭제
  src/main/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationController.kt
  src/main/kotlin/medinine/pill_buddy/domain/notification/service/NotificationService.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/service/NotificationServiceTest.kt
Labels: ✨ Feature, ✅ Test

#49 37: [REFACTOR]약 정보 검색
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/service/MedicationApiService.kt
Labels: 🔨 Refactor

#52 51: [FEAT] 네이버 소셜 로그인 기능
  build.gradle.kts
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/constant/KakaoProperty.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/constant/NaverProperty.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/controller/OAuthController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/KakaoUserResponse.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/NaverUserResponse.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/OAuthProfile.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/dto/OAuthTokenResponse.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoOAuthService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/OAuthClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/SocialLoginService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/UserReader.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/kakao/KakaoAuthClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/kakao/KakaoClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/kakao/KakaoProfileClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/naver/NaverAuthClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/naver/NaverClient.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/service/naver/NaverProfileClient.kt
  src/main/kotlin/medinine/pill_buddy/global/config/FeignConfig.kt
  src/main/kotlin/medinine/pill_buddy/global/exception/ErrorCode.kt
  src/main/resources/application.yml
  src/test/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoOAuthServiceTest.kt
  src/test/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#59 58: [DOCS] Swagger API 문서 작성
  src/main/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/caretaker/controller/CaretakerController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/controller/AuthController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/controller/UserController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/controller/OAuthController.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/profile/controller/ProfileController.kt
  src/main/kotlin/medinine/pill_buddy/domain/userMedication/controller/UserMedicationController.kt
Labels: 📃 Docs

#61 54:[FEAT] 타임리프를 통한 프론트엔드 구현
  build.gradle.kts
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/controller/MedicationApiController.kt
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/controller/MedicationWebController.kt
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/dto/MedicationForm.kt
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/dto/MyPageImpl.kt
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/service/MedicationApiService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/controller/OAuthController.kt
  src/main/resources/application.yml
  src/main/resources/static/LoginForm.html
  src/main/resources/static/afterLogin.html
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/medication/medication.html
  src/main/resources/templates/medication/medicationList.html
  src/main/resources/templates/medication/search.html
  src/test/kotlin/medinine/pill_buddy/domain/medicationApi/controller/MedicationApiControllerTest.kt
Labels: ✨ Feature

#64 [BUGFIX] 약 정보검색
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/controller/MedicationWebController.kt
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/service/MedicationApiService.kt
  src/main/resources/templates/medication/medicationList.html
  src/main/resources/templates/medication/search.html
Labels: 🐞 BugFix

#66 63: [DOCS] README 작성
  README.md
  src/test/kotlin/medinine/pill_buddy/domain/user/oauth/service/KakaoOAuthServiceTest.kt
Labels: 📃 Docs

#68 67: [REFACTOR] 시큐리티 권한 설정
  src/main/kotlin/medinine/pill_buddy/domain/user/oauth/controller/OAuthController.kt
  src/main/kotlin/medinine/pill_buddy/global/config/SecurityConfig.kt
Labels: ✨ Feature, 🔨 Refactor

#71 69:[BUGFIX] 약 정보 검색
  src/main/kotlin/medinine/pill_buddy/domain/medicationApi/service/MedicationApiService.kt
  src/test/kotlin/medinine/pill_buddy/domain/medicationApi/controller/MedicationApiControllerTest.kt
Labels: 🐞 BugFix

#73 72: [BUGFIX] 테스트 코드 사용자 인증 문제 해결
  src/main/kotlin/medinine/pill_buddy/domain/notification/service/NotificationService.kt
  src/main/kotlin/medinine/pill_buddy/domain/user/service/UserService.kt
  src/test/kotlin/medinine/pill_buddy/domain/notification/controller/NotificationControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/user/controller/UserControllerTest.kt
  src/test/kotlin/medinine/pill_buddy/domain/userMedication/controller/UserMedicationControllerTest.kt
Labels: 🐞 BugFix
